/**
 * Mobile coverage manifest. Every literal user-facing <Route> in App.tsx and a
 * module routes.tsx must have either direct coverage or a reviewed exemption.
 */
export interface MobileRouteCoverage {
  path: string;
  source: string;
  coverage: 'ratchet' | 'workflow' | 'exempt';
  detail: string;
}

export const MOBILE_ROUTE_COVERAGE: readonly MobileRouteCoverage[] = [
  {
    path: '/dashboard',
    source: 'src/App.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/learning',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/learning/:pathId',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail:
      'parameterized lesson view; every lesson renders one layout from learningPaths data, so /learning is the representative route and its controls come from the shared 44px form and button utilities',
  },
  { path: '/login', source: 'src/App.tsx', coverage: 'workflow', detail: 'login and MFA workflow' },
  {
    path: '/auth/callback',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/forgot-password',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/reset-password',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/privacy',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/terms',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/approvals/:token',
    source: 'src/App.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/action-items',
    source: 'src/modules/action-items/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/admin/errors',
    source: 'src/modules/admin/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin/analytics',
    source: 'src/modules/admin/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin/platform-analytics',
    source: 'src/modules/admin/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin/audit-log',
    source: 'src/modules/admin/routes.tsx',
    coverage: 'workflow',
    detail: 'administration approvals workflow',
  },
  {
    path: '/admin-hours',
    source: 'src/modules/admin-hours/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/admin-hours/categories/:categoryId/qr-code',
    source: 'src/modules/admin-hours/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin-hours/:categoryId/clock-in',
    source: 'src/modules/admin-hours/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin-hours/manage',
    source: 'src/modules/admin-hours/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/apparatus/print-labels',
    source: 'src/modules/apparatus/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/apparatus',
    source: 'src/modules/apparatus/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/apparatus/new',
    source: 'src/modules/apparatus/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/apparatus/:id',
    source: 'src/modules/apparatus/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/apparatus/:id/edit',
    source: 'src/modules/apparatus/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/communications/email-templates',
    source: 'src/modules/communications/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/communications/messages',
    source: 'src/modules/communications/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/communications/photo-use-consent',
    source: 'src/modules/communications/routes.tsx',
    coverage: 'exempt',
    detail:
      'admin roster behind notifications.manage; its table reflows to cards via rwd-table and every control comes from the shared 44px form utilities, so /messages remains the module representative',
  },
  {
    path: '/messages',
    source: 'src/modules/communications/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/documents',
    source: 'src/modules/documents/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/elections',
    source: 'src/modules/elections/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/elections/settings',
    source: 'src/modules/elections/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/elections/:electionId',
    source: 'src/modules/elections/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/ballot',
    source: 'src/modules/elections/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events',
    source: 'src/modules/events/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/events/:id',
    source: 'src/modules/events/routes.tsx',
    coverage: 'workflow',
    detail: 'event RSVP and check-in workflow',
  },
  {
    path: '/events/:id/qr-code',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/:id/check-in',
    source: 'src/modules/events/routes.tsx',
    coverage: 'workflow',
    detail: 'event RSVP and check-in workflow',
  },
  {
    path: '/events/templates',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/analytics',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/admin',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/:id/edit',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/:id/monitoring',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/:id/analytics',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/events/new',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/event-request/status/:token',
    source: 'src/modules/events/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/facilities/print-labels',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/facilities/maintenance',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/facilities/inspections',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/facilities/:id',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/facilities',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/locations',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/locations/qr-codes',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/apparatus-basic',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/display/:code',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/display/:code/events/:eventId/guest',
    source: 'src/modules/facilities/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/budgets',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/budgets/:id',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/settings',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/settings/approval-chains',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/purchase-requests',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/purchase-requests/new',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/purchase-requests/:id',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/purchase-requests/:id/edit',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/expenses',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/expenses/new',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/expenses/:id',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/check-requests',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/check-requests/new',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/check-requests/:id',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/finance/dues',
    source: 'src/modules/finance/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/forms',
    source: 'src/modules/forms/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/f/:slug',
    source: 'src/modules/forms/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/governance/org-chart',
    source: 'src/modules/governance/routes.tsx',
    coverage: 'ratchet',
    detail: 'member-facing chain of command; indented outline must stay readable in one column on a phone',
  },
  {
    path: '/governance/legal',
    source: 'src/modules/governance/routes.tsx',
    coverage: 'exempt',
    detail: 'administrative legal-content editor; public legal pages provide representative mobile coverage',
  },
  {
    path: '/grants',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/opportunities',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/applications',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/applications/new',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/applications/:id',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/applications/:id/edit',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/campaigns',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/donors',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/donations',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/grants/reports',
    source: 'src/modules/grants-fundraising/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/integrations',
    source: 'src/modules/integrations/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/inventory/my-equipment',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/inventory/admin',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/setup',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/items',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/pool',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/categories',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/maintenance',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/members',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/charges',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/returns',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/requests',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/write-offs',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/reorder',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/kits',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/variant-groups',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/allowances',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/vendors',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/admin/impact-planner',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/checkouts',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'workflow',
    detail: 'inventory scan and checkout workflow',
  },
  {
    path: '/inventory/storage-areas',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/import',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/items',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/items/:id',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/inventory/print-labels',
    source: 'src/modules/inventory/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/ip-security',
    source: 'src/modules/ip-security/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/ip-security/my-requests',
    source: 'src/modules/ip-security/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/medical-screening',
    source: 'src/modules/medical-screening/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/medical-supplies',
    source: 'src/modules/medical-supplies/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/medical-supplies/categories',
    source: 'src/modules/medical-supplies/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/members/print-labels',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/scan',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'workflow',
    detail: 'member lookup workflow',
  },
  {
    path: '/members/:userId',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/:userId/training',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/:userId/id-card',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/check-in-station',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/members/admin',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/members/admin/edit/:userId',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/admin/history/:userId',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/members/admin/waivers',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin/members',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/members/add',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/members/import',
    source: 'src/modules/membership/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/minutes',
    source: 'src/modules/minutes/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/minutes/:minutesId',
    source: 'src/modules/minutes/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/notifications',
    source: 'src/modules/notifications/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/start',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/department',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/onboarding/stations',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/apparatus',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/navigation-choice',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/email-platform',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/email-config',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/file-storage',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/file-storage-config',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/authentication',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/it-team',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/positions',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/onboarding/roles',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/onboarding/modules',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/modules/:moduleId/config',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/module-selection',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/system-owner',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/onboarding/admin-user',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/onboarding/complete',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/onboarding/security-check',
    source: 'src/modules/onboarding/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/prospective-members/print-labels',
    source: 'src/modules/prospective-members/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/prospective-members',
    source: 'src/modules/prospective-members/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/prospective-members/settings',
    source: 'src/modules/prospective-members/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/prospective-members/:applicantId/interview',
    source: 'src/modules/prospective-members/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/application-status/:token',
    source: 'src/modules/prospective-members/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/admin/public-portal',
    source: 'src/modules/public-portal/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/reports',
    source: 'src/modules/reports/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/scheduling/templates',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/patterns',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/reports',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/scheduling/settings',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/qualifications',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/platoons',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment-check-templates/new',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment-check-templates/:templateId',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment-check-reports',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/supply/expiring',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/apparatus-inventory',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment/checks',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/equipment/:apparatusId',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/checkin',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/checkin/print',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/scheduling/shift-reports/print',
    source: 'src/modules/scheduling/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/settings',
    source: 'src/modules/settings/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/settings/roles',
    source: 'src/modules/settings/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/setup',
    source: 'src/modules/settings/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/account',
    source: 'src/modules/settings/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/settings/account',
    source: 'src/modules/settings/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/store',
    source: 'src/modules/storefront/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/store/checkout',
    source: 'src/modules/storefront/routes.tsx',
    coverage: 'exempt',
    detail:
      'reachable only with a cart, which is deliberately unpersisted — an empty cart redirects to /store, so a ratchet entry would silently re-measure the catalog and read as coverage it is not. Its mobile layout (sticky total + submit bar, stacked payment and fulfilment tiles) is covered by CheckoutPage.test.tsx.',
  },
  {
    path: '/store/orders',
    source: 'src/modules/storefront/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/store/admin',
    source: 'src/modules/storefront/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/my-training',
    source: 'src/modules/training/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/training/submit',
    source: 'src/modules/training/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/training/courses',
    source: 'src/modules/training/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/training/programs',
    source: 'src/modules/training/routes.tsx',
    coverage: 'ratchet',
    detail: 'fast route-level mobile presentation ratchet',
  },
  {
    path: '/training/programs/:programId',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/my-progress/:enrollmentId',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/my-skill-tests/:testId',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/cohorts',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/cohorts/:cohortId',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/admin',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/compliance-config',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/officer',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/submissions',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/requirements',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/sessions/new',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/programs/new',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/shift-reports',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/integrations',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'legacy redirect; destination is inventoried',
  },
  {
    path: '/training/log-shift',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/templates/new',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/templates/:id',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/templates/:id/edit',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/test/new',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/test/:testId',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/test/:testId/active',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/print/member',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/print/program',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/print/compliance',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/print/template',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
  {
    path: '/training/skills-testing/print/scorecard',
    source: 'src/modules/training/routes.tsx',
    coverage: 'exempt',
    detail: 'secondary, parameterized, print, setup, or public route; covered by its representative module route',
  },
];
