/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        theme: {
          'bg-from': 'var(--bg-gradient-from)',
          'bg-via': 'var(--bg-gradient-via)',
          'bg-to': 'var(--bg-gradient-to)',
          'surface': 'var(--surface-bg)',
          'surface-secondary': 'var(--surface-secondary)',
          'surface-hover': 'var(--surface-hover)',
          'surface-border': 'var(--surface-border)',
          'surface-modal': 'var(--surface-modal)',
          'text-primary': 'var(--text-primary)',
          'text-secondary': 'var(--text-secondary)',
          'text-muted': 'var(--text-muted)',
          'nav-bg': 'var(--nav-bg)',
          'nav-border': 'var(--nav-border)',
          'input-bg': 'var(--input-bg)',
          'input-border': 'var(--input-border)',
          // Accent colors (AA-compliant text/icons on surfaces)
          'accent-red': 'var(--accent-red)',
          'accent-green': 'var(--accent-green)',
          'accent-blue': 'var(--accent-blue)',
          'accent-orange': 'var(--accent-orange)',
          'accent-yellow': 'var(--accent-yellow)',
          'accent-cyan': 'var(--accent-cyan)',
          'accent-purple': 'var(--accent-purple)',
          'accent-green-muted': 'var(--accent-green-muted)',
          'accent-orange-muted': 'var(--accent-orange-muted)',
          'focus-ring': 'var(--focus-ring)',
          // Toast colors
          'toast-success': 'var(--toast-success)',
          'toast-error': 'var(--toast-error)',
          'toast-warning-bg': 'var(--toast-warning-bg)',
          'toast-warning-text': 'var(--toast-warning-text)',
          // Status indicator colors
          'status-passed': 'var(--status-passed)',
          'status-failed': 'var(--status-failed)',
          'status-pending': 'var(--status-pending)',
          // Alert variants
          'alert-info-bg': 'var(--alert-info-bg)',
          'alert-info-border': 'var(--alert-info-border)',
          'alert-info-icon': 'var(--alert-info-icon)',
          'alert-info-title': 'var(--alert-info-title)',
          'alert-info-text': 'var(--alert-info-text)',
          'alert-success-bg': 'var(--alert-success-bg)',
          'alert-success-border': 'var(--alert-success-border)',
          'alert-success-icon': 'var(--alert-success-icon)',
          'alert-success-title': 'var(--alert-success-title)',
          'alert-success-text': 'var(--alert-success-text)',
          'alert-warning-bg': 'var(--alert-warning-bg)',
          'alert-warning-border': 'var(--alert-warning-border)',
          'alert-warning-icon': 'var(--alert-warning-icon)',
          'alert-warning-title': 'var(--alert-warning-title)',
          'alert-warning-text': 'var(--alert-warning-text)',
          'alert-purple-bg': 'var(--alert-purple-bg)',
          'alert-purple-border': 'var(--alert-purple-border)',
          'alert-purple-icon': 'var(--alert-purple-icon)',
          'alert-purple-title': 'var(--alert-purple-title)',
          'alert-purple-text': 'var(--alert-purple-text)',
          'alert-danger-bg': 'var(--alert-danger-bg)',
          'alert-danger-border': 'var(--alert-danger-border)',
          'alert-danger-icon': 'var(--alert-danger-icon)',
          'alert-danger-title': 'var(--alert-danger-title)',
          'alert-danger-text': 'var(--alert-danger-text)',
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
      animation: {
        'fade-in': 'fadeIn 1s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'success-pop': 'successPop 0.4s ease-out',
        'success-check': 'successCheck 0.3s ease-out 0.2s both',
        'success-draw': 'successDraw 0.4s ease-out 0.3s both',
        'page-enter': 'pageEnter 0.15s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        successPop: {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        successCheck: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        successDraw: {
          '0%': { 'stroke-dashoffset': '24', 'stroke-dasharray': '24' },
          '100%': { 'stroke-dashoffset': '0', 'stroke-dasharray': '24' },
        },
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
