"""
Database Models

Exports all SQLAlchemy models for the application.
"""

from app.models.analytics import AnalyticsEvent
from app.models.apparatus import (
    Apparatus,
    ApparatusCategory,
    ApparatusCustomField,
    ApparatusDocument,
    ApparatusEquipment,
    ApparatusFuelLog,
    ApparatusLocationHistory,
    ApparatusMaintenance,
    ApparatusMaintenanceType,
    ApparatusNFPACompliance,
    ApparatusOperator,
    ApparatusPhoto,
    ApparatusReportConfig,
    ApparatusStatus,
    ApparatusStatusHistory,
    ApparatusType,
    CustomFieldType,
    DefaultApparatusStatus,
    DefaultApparatusType,
    FuelType,
    MaintenanceCategory,
    MaintenanceIntervalUnit,
)
from app.models.audit import AuditLog, AuditLogCheckpoint, SeverityLevel
from app.models.document import (
    SYSTEM_FOLDERS,
    Document,
    DocumentFolder,
    DocumentStatus,
    DocumentType,
)
from app.models.election import Candidate, Election, ElectionStatus, Vote, VotingToken
from app.models.email_template import EmailAttachment, EmailTemplate, EmailTemplateType
from app.models.error_log import ErrorLog
from app.models.event import (
    CheckInWindowType,
    Event,
    EventExternalAttendee,
    EventRSVP,
    EventType,
    RSVPStatus,
)
from app.models.facilities import (
    DefaultFacilityStatus,
    DefaultFacilityType,
    Facility,
    FacilityAccessKey,
    FacilityCapitalProject,
    FacilityCategory,
    FacilityComplianceChecklist,
    FacilityComplianceItem,
    FacilityDocument,
    FacilityEmergencyContact,
    FacilityInspection,
    FacilityInsurancePolicy,
    FacilityMaintenance,
    FacilityMaintenanceType,
    FacilityOccupant,
    FacilityPhoto,
    FacilityRoom,
    FacilityShutoffLocation,
    FacilityStatus,
    FacilitySystem,
    FacilityType,
    FacilityUtilityAccount,
    FacilityUtilityReading,
)
from app.models.forms import (
    FieldType,
    Form,
    FormCategory,
    FormField,
    FormIntegration,
    FormStatus,
    FormSubmission,
    IntegrationTarget,
    IntegrationType,
)
from app.models.integration import Integration
from app.models.inventory import (
    AssignmentType,
    CheckOutRecord,
    InventoryCategory,
    InventoryItem,
    ItemAssignment,
    ItemCondition,
    ItemStatus,
    ItemType,
)
from app.models.inventory import MaintenanceRecord as InventoryMaintenanceRecord
from app.models.inventory import (
    StorageArea,
    StorageLocationType,
)
from app.models.ip_security import (
    BlockedAccessAttempt,
    CountryBlockRule,
    IPException,
    IPExceptionApprovalStatus,
    IPExceptionAuditLog,
    IPExceptionType,
)
from app.models.location import Location
from app.models.meeting import (
    ActionItemStatus,
    Meeting,
    MeetingActionItem,
    MeetingAttendee,
    MeetingStatus,
    MeetingType,
)
from app.models.membership_pipeline import (
    ActionType,
    MembershipPipeline,
    MembershipPipelineStep,
    PipelineStepType,
    ProspectActivityLog,
    ProspectiveMember,
    ProspectStatus,
    ProspectStepProgress,
    StepProgressStatus,
)
from app.models.minute import (
    ActionItem,
    ActionItemPriority,
    MeetingMinutes,
    MinutesActionItemStatus,
    MinutesMeetingType,
    MinutesStatus,
    MinutesTemplate,
    Motion,
    MotionStatus,
)
from app.models.notification import (
    DepartmentMessage,
    DepartmentMessageRead,
    MessagePriority,
    MessageTargetType,
    NotificationCategory,
    NotificationChannel,
    NotificationLog,
    NotificationRule,
    NotificationTrigger,
)
from app.models.onboarding import OnboardingChecklistItem, OnboardingStatus
from app.models.operational_rank import OperationalRank
from app.models.public_portal import (
    PublicPortalAccessLog,
    PublicPortalAPIKey,
    PublicPortalConfig,
    PublicPortalDataWhitelist,
)
from app.models.skills_testing import SkillTemplate, SkillTest
from app.models.training import (
    ExternalCategoryMapping,
    ExternalTrainingImport,
    ExternalTrainingProvider,
    ExternalTrainingSyncLog,
    ExternalUserMapping,
    ProgramEnrollment,
    ProgramMilestone,
    ProgramPhase,
    ProgramRequirement,
    RequirementProgress,
    Shift,
    ShiftAttendance,
    ShiftCall,
    SkillCheckoff,
    SkillEvaluation,
    TrainingApproval,
    TrainingCategory,
    TrainingCourse,
    TrainingProgram,
    TrainingRecord,
    TrainingRequirement,
    TrainingSession,
)
from app.models.user import (
    LeaveType,
    MemberLeaveOfAbsence,
    Organization,
    Role,
    Session,
    User,
    UserStatus,
    user_roles,
)

__all__ = [
    # User models
    "Organization",
    "User",
    "Role",
    "Session",
    "UserStatus",
    "user_roles",
    "MemberLeaveOfAbsence",
    "LeaveType",
    # Audit models
    "AuditLog",
    "AuditLogCheckpoint",
    "SeverityLevel",
    # Onboarding models
    "OnboardingStatus",
    "OnboardingChecklistItem",
    # Email template models
    "EmailTemplate",
    "EmailAttachment",
    "EmailTemplateType",
    # Location models
    "Location",
    # Public Portal models
    "PublicPortalConfig",
    "PublicPortalAPIKey",
    "PublicPortalAccessLog",
    "PublicPortalDataWhitelist",
    # Forms models
    "Form",
    "FormField",
    "FormSubmission",
    "FormIntegration",
    "FormStatus",
    "FormCategory",
    "FieldType",
    "IntegrationTarget",
    "IntegrationType",
    # Document models
    "Document",
    "DocumentFolder",
    "DocumentStatus",
    "DocumentType",
    "SYSTEM_FOLDERS",
    # Meeting models
    "Meeting",
    "MeetingAttendee",
    "MeetingActionItem",
    "MeetingType",
    "MeetingStatus",
    "ActionItemStatus",
    # Notification models
    "NotificationRule",
    "NotificationLog",
    "NotificationTrigger",
    "NotificationCategory",
    "NotificationChannel",
    # Department message models
    "DepartmentMessage",
    "DepartmentMessageRead",
    "MessagePriority",
    "MessageTargetType",
    # Integration models
    "Integration",
    # Analytics models
    "AnalyticsEvent",
    # Error log models
    "ErrorLog",
    # Apparatus models
    "Apparatus",
    "ApparatusType",
    "ApparatusStatus",
    "ApparatusCustomField",
    "ApparatusPhoto",
    "ApparatusDocument",
    "ApparatusMaintenanceType",
    "ApparatusMaintenance",
    "ApparatusFuelLog",
    "ApparatusOperator",
    "ApparatusEquipment",
    "ApparatusLocationHistory",
    "ApparatusStatusHistory",
    "ApparatusNFPACompliance",
    "ApparatusReportConfig",
    # Apparatus enums
    "ApparatusCategory",
    "DefaultApparatusType",
    "DefaultApparatusStatus",
    "FuelType",
    "CustomFieldType",
    "MaintenanceCategory",
    "MaintenanceIntervalUnit",
    # Minutes models
    "MeetingMinutes",
    "MinutesTemplate",
    "Motion",
    "ActionItem",
    "MinutesMeetingType",
    "MinutesStatus",
    "MotionStatus",
    "MinutesActionItemStatus",
    "ActionItemPriority",
    # Election models
    "Election",
    "Candidate",
    "VotingToken",
    "Vote",
    "ElectionStatus",
    # Event models
    "Event",
    "EventRSVP",
    "EventExternalAttendee",
    "EventType",
    "RSVPStatus",
    "CheckInWindowType",
    # Training models
    "TrainingCategory",
    "TrainingCourse",
    "TrainingRecord",
    "TrainingRequirement",
    "TrainingSession",
    "TrainingApproval",
    "TrainingProgram",
    "ProgramPhase",
    "ProgramRequirement",
    "ProgramMilestone",
    "ProgramEnrollment",
    "RequirementProgress",
    "SkillEvaluation",
    "SkillCheckoff",
    "ExternalTrainingProvider",
    "ExternalCategoryMapping",
    "ExternalUserMapping",
    "ExternalTrainingSyncLog",
    "ExternalTrainingImport",
    "Shift",
    "ShiftAttendance",
    "ShiftCall",
    # Skills testing models
    "SkillTemplate",
    "SkillTest",
    # Inventory models
    "InventoryCategory",
    "InventoryItem",
    "ItemAssignment",
    "CheckOutRecord",
    "InventoryMaintenanceRecord",
    "ItemType",
    "ItemCondition",
    "ItemStatus",
    "AssignmentType",
    "StorageArea",
    "StorageLocationType",
    # Membership pipeline models
    "MembershipPipeline",
    "MembershipPipelineStep",
    "ProspectiveMember",
    "ProspectStepProgress",
    "ProspectActivityLog",
    "PipelineStepType",
    "ActionType",
    "ProspectStatus",
    "StepProgressStatus",
    # IP Security models
    "IPException",
    "BlockedAccessAttempt",
    "CountryBlockRule",
    "IPExceptionAuditLog",
    "IPExceptionType",
    "IPExceptionApprovalStatus",
    # Operational rank models
    "OperationalRank",
    # Facilities models
    "FacilityType",
    "FacilityStatus",
    "Facility",
    "FacilityPhoto",
    "FacilityDocument",
    "FacilityMaintenanceType",
    "FacilityMaintenance",
    "FacilitySystem",
    "FacilityInspection",
    "FacilityUtilityAccount",
    "FacilityUtilityReading",
    "FacilityAccessKey",
    "FacilityRoom",
    "FacilityEmergencyContact",
    "FacilityShutoffLocation",
    "FacilityCapitalProject",
    "FacilityInsurancePolicy",
    "FacilityOccupant",
    "FacilityComplianceChecklist",
    "FacilityComplianceItem",
    "FacilityCategory",
    "DefaultFacilityType",
    "DefaultFacilityStatus",
]
