/**
 * What the registry actually seeds each system position with, as the position
 * editor's two checkboxes.
 *
 * GENERATED — do not edit by hand. Run:
 *
 *     cd backend && python3 scripts/generate_seeded_position_grants.py
 *
 * The editor saves whatever its boxes say, so its presented default is
 * load-bearing: a box ticked here that the backend does not seed is a grant
 * every department receives on its first Continue, and one left clear that the
 * backend does seed is a grant silently revoked. Deriving the defaults from
 * module category instead of from the registry did both — see
 * `backend/tests/test_seeded_position_grants.py`, which regenerates this file
 * and fails on any difference.
 *
 * Positions absent from this map are not seeded by the backend
 * (`DEFAULT_POSITIONS`); the editor's role-type heuristics still supply their
 * defaults, and saving one creates the position rather than updating a
 * seeded row.
 */
export interface SeededPositionGrant {
  view: readonly string[];
  manage: readonly string[];
}

export const SEEDED_POSITION_GRANTS: Readonly<Record<string, SeededPositionGrant>> = {
  apparatus_officer: {
    view: ['members', 'inventory', 'apparatus', 'storefront', 'positions'],
    manage: ['inventory', 'storefront'],
  },
  assistant_chief: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'minutes',
      'notifications',
      'prospective_members',
    ],
  },
  assistant_secretary: {
    view: ['members', 'events', 'documents', 'storefront', 'minutes', 'notifications', 'positions', 'settings'],
    manage: ['members', 'documents', 'minutes'],
  },
  board_of_directors: {
    view: [
      'members',
      'documents',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'positions',
      'settings',
    ],
    manage: ['reports'],
  },
  captain: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: ['members', 'training', 'scheduling', 'prospective_members'],
  },
  communications_officer: {
    view: ['members', 'events', 'documents', 'storefront', 'notifications', 'positions'],
    manage: ['events', 'notifications'],
  },
  deputy_chief: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'notifications',
      'integrations',
      'prospective_members',
    ],
  },
  ems_supply_officer: {
    view: ['members', 'apparatus', 'storefront', 'positions'],
    manage: [],
  },
  emt: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
    ],
    manage: [],
  },
  engineer: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
    ],
    manage: [],
  },
  facilities_manager: {
    view: ['members', 'inventory', 'facilities', 'storefront', 'notifications', 'positions'],
    manage: ['inventory', 'facilities', 'storefront'],
  },
  fire_chief: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'notifications',
      'integrations',
      'prospective_members',
      'settings',
    ],
  },
  firefighter: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
    ],
    manage: [],
  },
  fundraising_chair: {
    view: ['members', 'events', 'documents', 'storefront', 'reports', 'notifications'],
    manage: ['reports'],
  },
  historian: {
    view: ['members', 'events', 'documents', 'storefront', 'minutes', 'notifications'],
    manage: ['documents'],
  },
  it_manager: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'medical_supplies',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'mobile',
      'integrations',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'medical_supplies',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'mobile',
      'integrations',
      'prospective_members',
      'positions',
      'settings',
    ],
  },
  lieutenant: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'prospective_members',
      'positions',
      'settings',
    ],
    manage: ['training', 'scheduling'],
  },
  meeting_hall_coordinator: {
    view: ['members', 'events', 'scheduling', 'storefront', 'notifications'],
    manage: ['events'],
  },
  member: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'storefront',
      'elections',
      'minutes',
    ],
    manage: [],
  },
  membership_coordinator: {
    view: ['members', 'events', 'storefront', 'notifications', 'positions', 'settings'],
    manage: ['members', 'prospective_members'],
  },
  president: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'positions',
      'settings',
    ],
    manage: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'integrations',
      'prospective_members',
      'settings',
    ],
  },
  public_outreach: {
    view: ['members', 'events', 'storefront', 'positions'],
    manage: ['events'],
  },
  quartermaster: {
    view: ['members', 'inventory', 'apparatus', 'facilities', 'storefront', 'positions', 'settings'],
    manage: ['inventory', 'storefront'],
  },
  safety_officer: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'apparatus',
      'facilities',
      'storefront',
      'reports',
      'notifications',
      'positions',
    ],
    manage: ['documents', 'forms', 'training', 'reports'],
  },
  scheduling_officer: {
    view: ['members', 'events', 'scheduling', 'storefront', 'notifications', 'positions'],
    manage: ['scheduling'],
  },
  secretary: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'positions',
      'settings',
    ],
    manage: ['members', 'events', 'documents', 'forms', 'elections', 'minutes', 'reports', 'prospective_members'],
  },
  training_officer: {
    view: [
      'members',
      'events',
      'documents',
      'training',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'reports',
      'notifications',
      'positions',
    ],
    manage: ['events', 'training', 'reports'],
  },
  treasurer: {
    view: ['members', 'documents', 'facilities', 'storefront', 'reports', 'notifications', 'positions', 'settings'],
    manage: ['documents', 'reports'],
  },
  vice_president: {
    view: [
      'members',
      'events',
      'documents',
      'forms',
      'training',
      'inventory',
      'scheduling',
      'apparatus',
      'facilities',
      'storefront',
      'elections',
      'minutes',
      'reports',
      'notifications',
      'positions',
      'settings',
    ],
    manage: ['members', 'elections', 'minutes', 'reports', 'prospective_members'],
  },
};
