"""
Tests for the department office directory (app/services/officer_service.py)
and its injection into rendered email templates.

The directory turns "who is the President" into ``{{president_name}}`` so a
notice generated by any member is still signed by the officeholder. The
resolution precedence (override > linked member > position auto-detection)
and the render-time injection are the parts worth pinning down; both are
pure logic over already-loaded rows, so no database is needed.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock

from app.core.constants import (
    OFFICE_CATALOG,
    OFFICE_KEYS,
    OFFICE_VARIABLE_NAMES,
    ORG_SETTINGS_OFFICER_KEY,
)
from app.services.email_template_service import EmailTemplateService
from app.services.officer_service import (
    OfficerService,
    build_office_variables,
    resolve_office,
)

PRESIDENT = {
    "key": "president",
    "label": "President",
    "default_title": "President",
    "category": "administrative",
    "position_slugs": ["president"],
}


def _member(uid, first, last, email="", phone=""):
    return SimpleNamespace(
        id=uid, first_name=first, last_name=last, email=email, phone=phone, username=""
    )


def _record(**overrides):
    base = {
        "user_id": None,
        "display_name": None,
        "title": None,
        "email": None,
        "phone": None,
    }
    base.update(overrides)
    return SimpleNamespace(**base)


def _office(key, **overrides):
    base = {
        "office_key": key,
        "label": key.replace("_", " ").title(),
        "category": "administrative",
        "default_title": key.replace("_", " ").title(),
        "position_slugs": [key],
        "user_id": None,
        "name": "",
        "title": key.replace("_", " ").title(),
        "email": "",
        "phone": "",
        "source": "unset",
        "auto_candidates": [],
    }
    base.update(overrides)
    return base


class TestOfficeCatalog:
    def test_every_office_contributes_four_variables(self):
        variables = build_office_variables()
        assert len(variables) == len(OFFICE_CATALOG) * 4

    def test_variable_names_match_the_declared_set(self):
        names = {v["name"] for v in build_office_variables()}
        assert names == set(OFFICE_VARIABLE_NAMES)

    def test_offices_the_user_asked_for_are_present(self):
        for key in (
            "president",
            "vice_president",
            "chief",
            "deputy_chief",
            "assistant_chief",
            "secretary",
        ):
            assert key in OFFICE_KEYS

    def test_office_keys_are_unique(self):
        assert len(OFFICE_KEYS) == len(set(OFFICE_KEYS))


class TestResolutionPrecedence:
    def test_auto_detects_from_position_when_unassigned(self):
        holder = _member("u1", "Jane", "Doe", "jane@fd.org", "555-0100")
        out = resolve_office(PRESIDENT, None, None, [holder])
        assert out["source"] == "auto"
        assert out["name"] == "Jane Doe"
        assert out["email"] == "jane@fd.org"

    def test_assignment_beats_auto_detection(self):
        auto = _member("u1", "Jane", "Doe", "jane@fd.org")
        pinned = _member("u2", "Marcus", "Bell", "marcus@fd.org")
        out = resolve_office(PRESIDENT, _record(user_id="u2"), pinned, [auto, pinned])
        assert out["source"] == "assigned"
        assert out["name"] == "Marcus Bell"

    def test_override_beats_the_linked_members_values(self):
        member = _member("u1", "Jane", "Doe", "jane@fd.org", "555-0100")
        out = resolve_office(
            PRESIDENT,
            _record(user_id="u1", title="Madam President", email="office@fd.org"),
            member,
            [],
        )
        assert out["name"] == "Jane Doe"
        assert out["title"] == "Madam President"
        assert out["email"] == "office@fd.org"
        # The phone was not overridden, so it still follows the member record.
        assert out["phone"] == "555-0100"

    def test_name_only_assignment_needs_no_member_account(self):
        out = resolve_office(
            PRESIDENT, _record(display_name="Susan Whitfield"), None, []
        )
        assert out["source"] == "assigned"
        assert out["name"] == "Susan Whitfield"
        assert out["user_id"] is None

    def test_deleted_member_falls_back_to_auto_detection(self):
        # ondelete=SET NULL leaves the row behind with a dangling user_id;
        # reporting the office as filled-but-blank would silently strip the
        # signature from every notice that uses it.
        auto = _member("u2", "Marcus", "Bell")
        out = resolve_office(PRESIDENT, _record(user_id=None), None, [auto])
        assert out["source"] == "auto"
        assert out["name"] == "Marcus Bell"

    def test_vacant_office_reports_unset(self):
        out = resolve_office(PRESIDENT, None, None, [])
        assert out["source"] == "unset"
        assert out["name"] == ""
        # The title still falls back to the catalogue default.
        assert out["title"] == "President"

    def test_title_defaults_to_the_office_label(self):
        out = resolve_office(PRESIDENT, None, None, [_member("u1", "Jane", "Doe")])
        assert out["title"] == "President"

    def test_overrides_are_echoed_back_for_the_edit_form(self):
        member = _member("u1", "Jane", "Doe", "jane@fd.org")
        out = resolve_office(
            PRESIDENT, _record(user_id="u1", email="office@fd.org"), member, []
        )
        assert out["override_email"] == "office@fd.org"
        assert out["override_name"] is None

    def test_lists_every_position_holder_as_a_candidate(self):
        holders = [_member("u1", "Jane", "Doe"), _member("u2", "Marcus", "Bell")]
        out = resolve_office(PRESIDENT, None, None, holders)
        assert [c["name"] for c in out["auto_candidates"]] == [
            "Jane Doe",
            "Marcus Bell",
        ]

    def test_member_with_no_recorded_name_does_not_render_as_none_none(self):
        nameless = SimpleNamespace(
            id="u1",
            first_name=None,
            last_name=None,
            email="x@fd.org",
            phone="",
            username="jdoe",
        )
        out = resolve_office(PRESIDENT, None, None, [nameless])
        assert out["name"] == "jdoe"


class TestBuildContext:
    def test_flattens_offices_into_variables(self):
        context = OfficerService.build_context(
            [
                _office(
                    "president",
                    name="Jane Doe",
                    title="President",
                    email="jane@fd.org",
                    phone="555-0100",
                )
            ]
        )
        assert context["president_name"] == "Jane Doe"
        assert context["president_title"] == "President"
        assert context["president_email"] == "jane@fd.org"
        assert context["president_phone"] == "555-0100"

    def test_vacant_office_yields_empty_strings_not_missing_keys(self):
        # A missing key would leave the raw {{treasurer_name}} placeholder in
        # any caller that falls back to built-in defaults.
        context = OfficerService.build_context([_office("treasurer")])
        assert context["treasurer_name"] == ""
        assert context["treasurer_email"] == ""


class TestRenderInjection:
    def _template(self, html):
        return SimpleNamespace(
            subject="Notice",
            html_body=html,
            text_body=None,
            css_styles=None,
        )

    def _org(self, directory=None):
        settings = {}
        if directory is not None:
            settings[ORG_SETTINGS_OFFICER_KEY] = directory
        return SimpleNamespace(
            name="Test FD",
            logo=None,
            phone=None,
            email=None,
            website=None,
            physical_address_same=True,
            settings=settings,
        )

    def test_directory_supplies_signature_variables(self):
        svc = EmailTemplateService(MagicMock())
        _, html, _ = svc.render(
            self._template("<p>{{president_name}}, {{president_title}}</p>"),
            {},
            organization=self._org(
                {"president_name": "Jane Doe", "president_title": "President"}
            ),
        )
        assert "Jane Doe, President" in html

    def test_caller_context_wins_over_directory(self):
        svc = EmailTemplateService(MagicMock())
        _, html, _ = svc.render(
            self._template("<p>{{president_name}}</p>"),
            {"president_name": "Explicit Override"},
            organization=self._org({"president_name": "Jane Doe"}),
        )
        assert "Explicit Override" in html
        assert "Jane Doe" not in html

    def test_unknown_settings_keys_are_not_injected(self):
        # The directory is admin-written data; only catalogued office
        # variables may reach the template context.
        svc = EmailTemplateService(MagicMock())
        _, html, _ = svc.render(
            self._template("<p>[{{arbitrary_key}}]</p>"),
            {},
            organization=self._org(
                {"president_name": "Jane Doe", "arbitrary_key": "injected"}
            ),
        )
        assert "injected" not in html
        assert "[]" in html

    def test_officer_name_is_html_escaped(self):
        svc = EmailTemplateService(MagicMock())
        _, html, _ = svc.render(
            self._template("<p>{{president_name}}</p>"),
            {},
            organization=self._org({"president_name": "<script>alert(1)</script>"}),
        )
        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html

    def test_missing_directory_renders_blank_not_placeholder(self):
        svc = EmailTemplateService(MagicMock())
        _, html, _ = svc.render(
            self._template("<p>[{{president_name}}]</p>"),
            {},
            organization=self._org(),
        )
        assert "{{president_name}}" not in html
        assert "[]" in html
