import React from 'react';

import { bodyText, calloutClass, listClass, sectionHeading } from './legalStyles';

/**
 * Built-in privacy notice shown when a department has not published its own
 * wording via organization settings ("legal.privacy_policy").
 *
 * Written for a US fire-service deployment: the department is the data
 * controller, records are frequently subject to statutory retention and to
 * state public-records law, and access is a function of membership status
 * rather than of anything the software decides. Departments in other
 * jurisdictions, or with counsel-reviewed wording of their own, replace this
 * text wholesale rather than editing it here.
 */
const DefaultPrivacyPolicy: React.FC<{ orgName: string }> = ({ orgName }) => (
  <>
    <p className={bodyText}>
      {orgName} (&ldquo;the department&rdquo;, &ldquo;we&rdquo;) operates this member intranet to run department
      operations — membership, training, scheduling, events, and related record keeping. The department is the data
      controller for the information in this system; The Logbook is the software it runs on. This notice describes what
      the system stores about you as a member or applicant, how it is used, and who decides.
    </p>

    <h2 className={sectionHeading}>The short version</h2>
    <ul className={listClass}>
      <li>The department owns this system, the records in it, and every account on it.</li>
      <li>
        Your access exists because of your status in the department, and it changes or ends when that status does.
      </li>
      <li>Information is collected to run the department — never sold, never used for advertising.</li>
      <li>Who sees what is set by role, and sensitive records are further restricted and access-audited.</li>
      <li>Much of what is stored here is an official department record, kept for as long as the law requires.</li>
      <li>Activity in the system is logged. Treat it as a department system, not a private one.</li>
    </ul>

    <h2 className={sectionHeading}>Who controls this system and your access</h2>
    <div className={calloutClass}>
      <p>
        <strong>{orgName} holds full control of this application and of the information in it.</strong> The Logbook is
        only the software the department runs; it does not decide who is admitted, what any role may see, or what
        becomes of a record.
      </p>
      <p className="mt-3">
        <strong>Access is based on your status within the department</strong>, determined by the department under its
        own rules, bylaws, standard operating procedures, membership policies, and the state and local laws it operates
        under. The department decides who is granted an account, which role each account carries and therefore what it
        can see, and when access is expanded, reduced, suspended, or ended. A change in your status — probationary to
        active, a leave of absence, a change of rank or assignment, a suspension, or separation from the department —
        changes or ends your access accordingly, and may take effect without prior notice. Nothing in this notice
        creates a right of access to this system, or to any record in it, independent of your standing in the
        department.
      </p>
    </div>

    <h2 className={sectionHeading}>Information we collect</h2>
    <ul className={listClass}>
      <li>
        <strong>Identity and contact details</strong> — name, email, phone, address, date of birth, photo, and
        membership identifiers.
      </li>
      <li>
        <strong>Emergency contacts</strong> — names and contact details you provide for use in an emergency.
      </li>
      <li>
        <strong>Operational records</strong> — training and certification history, event and shift attendance, service
        hours, equipment assignments, and meeting records.
      </li>
      <li>
        <strong>Health screening information</strong> — where your department uses the medical screening module,
        screening responses are stored encrypted and restricted to authorized medical/administrative roles.
      </li>
      <li>
        <strong>Applicant information</strong> — where you applied through the department, the application, references,
        and background-check status recorded during recruitment.
      </li>
      <li>
        <strong>Technical data</strong> — sign-in timestamps, IP addresses, device and browser information, and security
        audit records kept to protect member accounts and satisfy record-keeping obligations.
      </li>
    </ul>

    <h2 className={sectionHeading}>Where the information comes from</h2>
    <p className={bodyText}>
      Most of it comes from you — what you enter in your profile, an application, or a form. The rest is created by the
      department in the ordinary course of business (attendance an officer records, a certification an instructor signs
      off, a role an administrator assigns), generated by the system itself (sign-in and audit records), or supplied by
      a third party the department uses, such as a certification registry, a background-check provider, or a training
      body.
    </p>

    <h2 className={sectionHeading}>How it is used, and why</h2>
    <p className={bodyText}>
      Your information is used only to operate the department: verifying membership and qualifications, planning
      training and staffing, contacting you (including emergency contact use), meeting insurance and regulatory
      record-keeping requirements, and securing the system itself. The department relies on its need to run its
      operations, on the legal obligations it is subject to, and — for anything genuinely optional, such as text-message
      alerts — on your consent, which you can withdraw. It is not sold, and it is not used for advertising.
    </p>

    <h2 className={sectionHeading}>Who can see it</h2>
    <p className={bodyText}>
      Access is role-based: officers and administrators see what their role requires, and sensitive categories (such as
      health screening data) are further restricted and access-audited. Information may be shared with service providers
      that host or support the system, and where law, insurance requirements, or public-records obligations require it.
      Service providers act on the department&rsquo;s instructions and may not use member information for their own
      purposes.
    </p>

    <h2 className={sectionHeading}>Public records and legal disclosure</h2>
    <p className={bodyText}>
      Fire departments and the agencies they serve under are frequently subject to public-records, sunshine, and open
      meetings laws. Records held in this system — meeting minutes, rosters, incident and training documentation — may
      have to be produced in response to a public-records request, a subpoena, a court order, a lawful government
      request, or an audit or accreditation review. The department applies whatever exemptions the law provides for
      personal, medical, and security-sensitive information, but it cannot withhold what the law requires it to release.
    </p>

    <h2 className={sectionHeading}>Monitoring</h2>
    <p className={bodyText}>
      This is a department system, not a personal one. Sign-ins, record access, and changes are logged to a
      tamper-evident audit trail, and the department may review that trail for security, records, personnel, or legal
      purposes. You should not expect that your activity in this system, or content you place in it, is private from the
      department.
    </p>

    <h2 className={sectionHeading}>Security</h2>
    <p className={bodyText}>
      The system uses encrypted connections, encryption at rest for sensitive fields, role-based access control,
      multi-factor authentication, and a tamper-evident audit log. No system is perfectly secure. If you believe member
      information has been exposed, or you have found a security weakness, tell a department administrator right away.
    </p>

    <h2 className={sectionHeading}>If something goes wrong</h2>
    <p className={bodyText}>
      If a breach of member information occurs, the department will investigate, contain it, and notify affected people
      and any regulator or agency where notification is required — within the deadlines that apply to it, which for
      health information and for state breach-notification laws can be short.
    </p>

    <h2 className={sectionHeading}>Where information is stored</h2>
    <p className={bodyText}>
      The department chooses where this system runs and where its data is held; ask an administrator if you need to know
      the specifics for your department. If information is ever handled outside the country it was collected in, the
      department remains responsible for protecting it to the same standard described here.
    </p>

    <h2 className={sectionHeading}>Retention</h2>
    <p className={bodyText}>
      Operational records (training, attendance, minutes) are retained per the department&rsquo;s records-retention
      schedule and applicable statutes, which commonly require multi-year retention for fire-service records — and for
      certain exposure and medical-surveillance records, decades. Security audit records are retained for seven years by
      default. Retention is set by the department, and records it is legally obliged to keep are kept even if you ask
      for their deletion.
    </p>

    <h2 className={sectionHeading}>Members under 18</h2>
    <p className={bodyText}>
      Where the department runs a junior, cadet, or explorer program, accounts for members under 18 are created at the
      department&rsquo;s discretion with parent or guardian consent, and the same protections in this notice apply. A
      parent or guardian may ask the department to review, correct, or remove a minor&rsquo;s information, subject to
      the records the department must keep. This system is not directed to the general public and does not knowingly
      collect information from children outside a department program.
    </p>

    <h2 className={sectionHeading}>Your choices</h2>
    <ul className={listClass}>
      <li>You can review and update your profile and emergency contacts in Settings.</li>
      <li>You can control your notification preferences, and withdraw consent to text messages at any time.</li>
      <li>You can request an export of your personal data from the department.</li>
      <li>You can ask the department to correct information about you that is wrong.</li>
      <li>
        When you leave the department, you can ask for your personal details to be anonymized; operational records the
        department must legally keep are retained without your identifying details where the law allows.
      </li>
    </ul>
    <p className={bodyText}>
      Make any of these requests to a department administrator, who will respond within the time the applicable law
      allows. Requests are decided by the department, and may be limited by the records it is required to keep or
      produce. Depending on where you live you may have further rights under state or national privacy law, and the
      right to complain to your regulator.
    </p>

    <h2 className={sectionHeading}>What we do not do</h2>
    <p className={bodyText}>
      We do not sell or share your personal information for money or for cross-context behavioral advertising, we run no
      advertising or third-party tracking in this system, and no decision that materially affects you — membership,
      discipline, qualification — is made by automation alone without a person reviewing it.
    </p>

    <h2 className={sectionHeading}>Cookies</h2>
    <p className={bodyText}>
      The system uses essential cookies only: secure, httpOnly session cookies for sign-in and a CSRF-protection cookie.
      There are no advertising or cross-site tracking cookies.
    </p>

    <h2 className={sectionHeading}>Changes to this notice</h2>
    <p className={bodyText}>
      The department may update this notice as its practices, its systems, or the law change. The date at the top of
      this page shows when it was last revised; material changes will be communicated through normal department
      channels. Review it periodically.
    </p>

    <h2 className={sectionHeading}>Questions</h2>
    <p className={bodyText}>
      Contact your department&rsquo;s administrators with any privacy question or request. They are responsible for this
      deployment and its records.
    </p>
  </>
);

export default DefaultPrivacyPolicy;
