"""Seed apparatus system data

Revision ID: 20260203_0023
Revises: 20260203_0022
Create Date: 2026-02-03

Seeds system-defined apparatus types, statuses, and maintenance types
that are available to all organizations.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid

# revision identifiers, used by Alembic.
revision = '20260203_0023'
down_revision = '20260203_0022'
branch_labels = None
depends_on = None


def generate_uuid():
    return str(uuid.uuid4())


def upgrade() -> None:
    # Define table references
    apparatus_types = table(
        'apparatus_types',
        column('id', sa.String),
        column('organization_id', sa.String),
        column('name', sa.String),
        column('code', sa.String),
        column('description', sa.Text),
        column('category', sa.String),
        column('is_system', sa.Boolean),
        column('default_type', sa.String),
        column('icon', sa.String),
        column('color', sa.String),
        column('sort_order', sa.Integer),
        column('is_active', sa.Boolean),
    )

    apparatus_statuses = table(
        'apparatus_statuses',
        column('id', sa.String),
        column('organization_id', sa.String),
        column('name', sa.String),
        column('code', sa.String),
        column('description', sa.Text),
        column('is_system', sa.Boolean),
        column('default_status', sa.String),
        column('is_available', sa.Boolean),
        column('is_operational', sa.Boolean),
        column('requires_reason', sa.Boolean),
        column('is_archived_status', sa.Boolean),
        column('color', sa.String),
        column('icon', sa.String),
        column('sort_order', sa.Integer),
        column('is_active', sa.Boolean),
    )

    apparatus_maintenance_types = table(
        'apparatus_maintenance_types',
        column('id', sa.String),
        column('organization_id', sa.String),
        column('name', sa.String),
        column('code', sa.String),
        column('description', sa.Text),
        column('category', sa.String),
        column('is_system', sa.Boolean),
        column('default_interval_value', sa.Integer),
        column('default_interval_unit', sa.String),
        column('default_interval_miles', sa.Integer),
        column('default_interval_hours', sa.Integer),
        column('is_nfpa_required', sa.Boolean),
        column('nfpa_reference', sa.String),
        column('sort_order', sa.Integer),
        column('is_active', sa.Boolean),
    )

    # =========================================================================
    # Seed Apparatus Types
    # =========================================================================
    type_data = [
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Engine',
            'code': 'engine',
            'description': 'Fire engine/pumper with pump and hose capabilities',
            'category': 'fire',
            'is_system': True,
            'default_type': 'engine',
            'icon': 'fire-truck',
            'color': '#DC2626',
            'sort_order': 1,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Ladder/Aerial',
            'code': 'ladder',
            'description': 'Ladder truck with aerial device',
            'category': 'fire',
            'is_system': True,
            'default_type': 'ladder',
            'icon': 'ladder',
            'color': '#DC2626',
            'sort_order': 2,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Quint',
            'code': 'quint',
            'description': 'Combination engine and ladder apparatus',
            'category': 'fire',
            'is_system': True,
            'default_type': 'quint',
            'icon': 'fire-truck',
            'color': '#DC2626',
            'sort_order': 3,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Rescue',
            'code': 'rescue',
            'description': 'Heavy rescue or technical rescue unit',
            'category': 'rescue',
            'is_system': True,
            'default_type': 'rescue',
            'icon': 'shield',
            'color': '#F59E0B',
            'sort_order': 4,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Ambulance',
            'code': 'ambulance',
            'description': 'Emergency medical services transport unit',
            'category': 'ems',
            'is_system': True,
            'default_type': 'ambulance',
            'icon': 'ambulance',
            'color': '#3B82F6',
            'sort_order': 5,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Squad',
            'code': 'squad',
            'description': 'Multi-purpose squad/rapid intervention unit',
            'category': 'fire',
            'is_system': True,
            'default_type': 'squad',
            'icon': 'users',
            'color': '#DC2626',
            'sort_order': 6,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Tanker/Tender',
            'code': 'tanker',
            'description': 'Water supply tanker/tender',
            'category': 'fire',
            'is_system': True,
            'default_type': 'tanker',
            'icon': 'droplet',
            'color': '#0EA5E9',
            'sort_order': 7,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Brush/Wildland',
            'code': 'brush',
            'description': 'Brush truck for wildland firefighting',
            'category': 'fire',
            'is_system': True,
            'default_type': 'brush',
            'icon': 'tree',
            'color': '#22C55E',
            'sort_order': 8,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'HazMat',
            'code': 'hazmat',
            'description': 'Hazardous materials response unit',
            'category': 'rescue',
            'is_system': True,
            'default_type': 'hazmat',
            'icon': 'biohazard',
            'color': '#FBBF24',
            'sort_order': 9,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Command',
            'code': 'command',
            'description': 'Command/battalion chief vehicle',
            'category': 'command',
            'is_system': True,
            'default_type': 'command',
            'icon': 'radio',
            'color': '#FFFFFF',
            'sort_order': 10,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Utility',
            'code': 'utility',
            'description': 'General utility/support vehicle',
            'category': 'support',
            'is_system': True,
            'default_type': 'utility',
            'icon': 'truck',
            'color': '#6B7280',
            'sort_order': 11,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Boat',
            'code': 'boat',
            'description': 'Marine/water rescue vessel',
            'category': 'marine',
            'is_system': True,
            'default_type': 'boat',
            'icon': 'ship',
            'color': '#0284C7',
            'sort_order': 12,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'ATV/UTV',
            'code': 'atv',
            'description': 'All-terrain or utility task vehicle',
            'category': 'support',
            'is_system': True,
            'default_type': 'atv',
            'icon': 'car',
            'color': '#65A30D',
            'sort_order': 13,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Staff Vehicle',
            'code': 'staff',
            'description': 'Administrative/staff vehicle',
            'category': 'admin',
            'is_system': True,
            'default_type': 'staff',
            'icon': 'car',
            'color': '#6B7280',
            'sort_order': 14,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Reserve',
            'code': 'reserve',
            'description': 'Reserve/backup apparatus',
            'category': 'other',
            'is_system': True,
            'default_type': 'reserve',
            'icon': 'archive',
            'color': '#9CA3AF',
            'sort_order': 15,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Other',
            'code': 'other',
            'description': 'Other apparatus type',
            'category': 'other',
            'is_system': True,
            'default_type': 'other',
            'icon': 'more-horizontal',
            'color': '#6B7280',
            'sort_order': 99,
            'is_active': True,
        },
    ]

    op.bulk_insert(apparatus_types, type_data)

    # =========================================================================
    # Seed Apparatus Statuses
    # =========================================================================
    status_data = [
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'In Service',
            'code': 'in_service',
            'description': 'Apparatus is operational and available for response',
            'is_system': True,
            'default_status': 'in_service',
            'is_available': True,
            'is_operational': True,
            'requires_reason': False,
            'is_archived_status': False,
            'color': '#22C55E',
            'icon': 'check-circle',
            'sort_order': 1,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Out of Service',
            'code': 'out_of_service',
            'description': 'Apparatus is temporarily unavailable',
            'is_system': True,
            'default_status': 'out_of_service',
            'is_available': False,
            'is_operational': False,
            'requires_reason': True,
            'is_archived_status': False,
            'color': '#EF4444',
            'icon': 'x-circle',
            'sort_order': 2,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'In Maintenance',
            'code': 'in_maintenance',
            'description': 'Apparatus is undergoing scheduled or unscheduled maintenance',
            'is_system': True,
            'default_status': 'in_maintenance',
            'is_available': False,
            'is_operational': False,
            'requires_reason': False,
            'is_archived_status': False,
            'color': '#F59E0B',
            'icon': 'wrench',
            'sort_order': 3,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Reserve',
            'code': 'reserve',
            'description': 'Apparatus is in reserve/backup status',
            'is_system': True,
            'default_status': 'reserve',
            'is_available': True,
            'is_operational': True,
            'requires_reason': False,
            'is_archived_status': False,
            'color': '#3B82F6',
            'icon': 'archive',
            'sort_order': 4,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'On Order',
            'code': 'on_order',
            'description': 'Apparatus has been ordered but not yet delivered',
            'is_system': True,
            'default_status': 'on_order',
            'is_available': False,
            'is_operational': False,
            'requires_reason': False,
            'is_archived_status': False,
            'color': '#8B5CF6',
            'icon': 'clock',
            'sort_order': 5,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Sold',
            'code': 'sold',
            'description': 'Apparatus has been sold',
            'is_system': True,
            'default_status': 'sold',
            'is_available': False,
            'is_operational': False,
            'requires_reason': False,
            'is_archived_status': True,
            'color': '#6B7280',
            'icon': 'dollar-sign',
            'sort_order': 98,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Disposed',
            'code': 'disposed',
            'description': 'Apparatus has been disposed/retired',
            'is_system': True,
            'default_status': 'disposed',
            'is_available': False,
            'is_operational': False,
            'requires_reason': False,
            'is_archived_status': True,
            'color': '#6B7280',
            'icon': 'trash-2',
            'sort_order': 99,
            'is_active': True,
        },
    ]

    op.bulk_insert(apparatus_statuses, status_data)

    # =========================================================================
    # Seed Maintenance Types
    # =========================================================================
    maintenance_data = [
        # Preventive Maintenance
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Oil Change',
            'code': 'oil_change',
            'description': 'Engine oil and filter change',
            'category': 'preventive',
            'is_system': True,
            'default_interval_value': 3,
            'default_interval_unit': 'months',
            'default_interval_miles': 5000,
            'default_interval_hours': 250,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 1,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Tire Rotation',
            'code': 'tire_rotation',
            'description': 'Rotate tires and check pressure/wear',
            'category': 'preventive',
            'is_system': True,
            'default_interval_value': 6,
            'default_interval_unit': 'months',
            'default_interval_miles': 10000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 2,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Brake Inspection',
            'code': 'brake_inspection',
            'description': 'Inspect brake pads, rotors, and fluid',
            'category': 'inspection',
            'is_system': True,
            'default_interval_value': 6,
            'default_interval_unit': 'months',
            'default_interval_miles': 15000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 3,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Transmission Service',
            'code': 'transmission_service',
            'description': 'Transmission fluid and filter service',
            'category': 'preventive',
            'is_system': True,
            'default_interval_value': 2,
            'default_interval_unit': 'years',
            'default_interval_miles': 50000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 4,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Coolant Service',
            'code': 'coolant_service',
            'description': 'Engine coolant flush and refill',
            'category': 'preventive',
            'is_system': True,
            'default_interval_value': 2,
            'default_interval_unit': 'years',
            'default_interval_miles': 50000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 5,
            'is_active': True,
        },
        # Fire Apparatus Specific
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Pump Test',
            'code': 'pump_test',
            'description': 'Annual pump service test per NFPA 1911',
            'category': 'certification',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': True,
            'nfpa_reference': 'NFPA 1911',
            'sort_order': 10,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Aerial Device Test',
            'code': 'aerial_test',
            'description': 'Annual aerial device inspection and test',
            'category': 'certification',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': True,
            'nfpa_reference': 'NFPA 1911',
            'sort_order': 11,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Hose Test',
            'code': 'hose_test',
            'description': 'Annual fire hose testing',
            'category': 'certification',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': True,
            'nfpa_reference': 'NFPA 1962',
            'sort_order': 12,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Ground Ladder Test',
            'code': 'ladder_test',
            'description': 'Annual ground ladder inspection and test',
            'category': 'certification',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': True,
            'nfpa_reference': 'NFPA 1932',
            'sort_order': 13,
            'is_active': True,
        },
        # Inspections
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'DOT Inspection',
            'code': 'dot_inspection',
            'description': 'Department of Transportation annual inspection',
            'category': 'inspection',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 20,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'State Inspection',
            'code': 'state_inspection',
            'description': 'State vehicle safety inspection',
            'category': 'inspection',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 21,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Emissions Test',
            'code': 'emissions_test',
            'description': 'Vehicle emissions testing',
            'category': 'inspection',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 22,
            'is_active': True,
        },
        # EMS Specific
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Ambulance Inspection',
            'code': 'ambulance_inspection',
            'description': 'State ambulance licensing inspection',
            'category': 'inspection',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 30,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Cardiac Monitor Calibration',
            'code': 'monitor_calibration',
            'description': 'Cardiac monitor/defibrillator calibration and testing',
            'category': 'certification',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 31,
            'is_active': True,
        },
        # Fluids
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Hydraulic Fluid Service',
            'code': 'hydraulic_fluid',
            'description': 'Hydraulic system fluid check and service',
            'category': 'fluid',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'years',
            'default_interval_miles': None,
            'default_interval_hours': 500,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 40,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Power Steering Fluid',
            'code': 'power_steering_fluid',
            'description': 'Power steering fluid check and service',
            'category': 'fluid',
            'is_system': True,
            'default_interval_value': 2,
            'default_interval_unit': 'years',
            'default_interval_miles': 50000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 41,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Differential Fluid Service',
            'code': 'differential_fluid',
            'description': 'Differential gear oil change',
            'category': 'fluid',
            'is_system': True,
            'default_interval_value': 2,
            'default_interval_unit': 'years',
            'default_interval_miles': 50000,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 42,
            'is_active': True,
        },
        # General
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'General Repair',
            'code': 'general_repair',
            'description': 'General mechanical repair',
            'category': 'repair',
            'is_system': True,
            'default_interval_value': None,
            'default_interval_unit': None,
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 90,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Body/Paint Repair',
            'code': 'body_repair',
            'description': 'Body work and paint repair',
            'category': 'repair',
            'is_system': True,
            'default_interval_value': None,
            'default_interval_unit': None,
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 91,
            'is_active': True,
        },
        {
            'id': generate_uuid(),
            'organization_id': None,
            'name': 'Cleaning/Decon',
            'code': 'cleaning',
            'description': 'Vehicle cleaning and decontamination',
            'category': 'cleaning',
            'is_system': True,
            'default_interval_value': 1,
            'default_interval_unit': 'weeks',
            'default_interval_miles': None,
            'default_interval_hours': None,
            'is_nfpa_required': False,
            'nfpa_reference': None,
            'sort_order': 92,
            'is_active': True,
        },
    ]

    op.bulk_insert(apparatus_maintenance_types, maintenance_data)


def downgrade() -> None:
    # Delete all seeded system data
    op.execute("DELETE FROM apparatus_maintenance_types WHERE is_system = 1")
    op.execute("DELETE FROM apparatus_statuses WHERE is_system = 1")
    op.execute("DELETE FROM apparatus_types WHERE is_system = 1")
