"""Backfill the storefront grants onto existing organizations' positions

The department store is unreachable for a regular member on any department
that onboarded before the storefront grants were added to the registry.

``DEFAULT_POSITIONS`` is materialized into the ``positions`` table only when an
organization is onboarded, so a grant added to the registry afterwards reaches
fresh installs and nobody else. ``storefront.view`` / ``storefront.order`` were
added to ``DEFAULT_POSITIONS["member"]`` after the storefront module shipped,
and no migration ever wrote them to the rows already stored.

Why this is invisible for the people who would report it: ``dependencies.py``
unions each assigned position's *stored* permissions with the member's
operational rank defaults, and rank defaults resolve at runtime from
``OPERATIONAL_RANKS`` — no table involved. So every officer, and every member
carrying a rank, holds ``storefront.view`` regardless of this migration. The
members who cannot open the store are the ones with **no operational rank**:
administrative, social and support members, plus anyone whose rank was simply
never set. They hold only the stale stored ``member`` position, and
``ProtectedRoute`` sends them away from a store the navigation still shows.

Mirrors the grants in ``app/core/permissions.py`` exactly, and follows the
precedent of ``20260816_0005`` (medical supplies) and ``20260824_2140``
(compliance.view).

**``is_system = True`` does not mean "untouched".** ``RoleService.update_role``
deliberately allows a system position's ``permissions`` to be edited in place —
its docstring reads "System roles can only have their permissions and
description updated" — so the flag stays ``True`` on a position a department has
customized. Scoping on it alone would hand ``storefront.manage`` back to a
quartermaster whose department had deliberately withdrawn it.

So a row is rewritten only when its stored permission set still equals the
registry default this migration was written against, spelled out in
``_PRIOR_DEFAULTS`` below. Anything else — a grant added, one removed, the set
replaced wholesale — is the department's own decision and is left alone; they
grant it themselves in Role Management. Skipping costs those departments the
status quo, not a regression.

``_PRIOR_DEFAULTS`` is frozen rather than imported, for the reason the inlined
normalizer in ``20260819_2037_1eeb053d59b7`` is: a migration must keep matching
the rows it was written to match after the registry moves on.
``test_storefront_grant_backfill.py`` fails if the two drift.

Idempotent: a row already carrying the grants no longer equals the prior
default, so it is skipped — which is also why this is safe to re-run.

Revision ID: a4f8c1b92d17
Revises: c4a91b7e2f08
Create Date: 2026-08-25 15:00:00.000000
"""

import json

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4f8c1b92d17"
down_revision = "c4a91b7e2f08"
branch_labels = None
depends_on = None


_VIEW_ORDER = ("storefront.view", "storefront.order")
_FULL = _VIEW_ORDER + ("storefront.manage",)

# slug -> grants to add. Mirrors DEFAULT_POSITIONS in app/core/permissions.py.
# ``it_manager`` is absent on purpose: it seeds with the "*" wildcard, which
# already covers every storefront permission.
_BACKFILL: dict[str, tuple[str, ...]] = {
    # Every member of the department can browse and order.
    "member": _VIEW_ORDER,
    # Rank-mirroring system positions (see permissions.py — DEFAULT_POSITIONS
    # aliases OPERATIONAL_RANKS for these, so onboarding stores a copy).
    "firefighter": _VIEW_ORDER,
    "engineer": _VIEW_ORDER,
    "lieutenant": _VIEW_ORDER,
    "captain": _VIEW_ORDER,
    "fire_chief": _FULL,
    "deputy_chief": _FULL,
    "assistant_chief": _FULL,
    # Corporate positions.
    "president": _FULL,
    "vice_president": _VIEW_ORDER,
    "quartermaster": _FULL,
    "apparatus_officer": _FULL,
    "facilities_manager": _FULL,
    "safety_officer": _VIEW_ORDER,
}


# Snapshot of DEFAULT_POSITIONS at this revision, minus the grants added
# above — i.e. what a pristine stored row looks like when this runs.
_PRIOR_DEFAULTS: dict[str, set[str]] = {
    "member": {
        "apparatus.view",
        "documents.view",
        "elections.view",
        "equipment_check.submit",
        "events.view",
        "facilities.view",
        "forms.view",
        "inventory.view",
        "locations.view",
        "meetings.view",
        "members.view",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "scheduling.swap",
        "scheduling.view",
        "training.view",
    },
    "firefighter": {
        "apparatus.view",
        "documents.view",
        "elections.view",
        "events.view",
        "facilities.view",
        "forms.view",
        "inventory.view",
        "locations.view",
        "meetings.view",
        "members.view",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "scheduling.swap",
        "scheduling.view",
        "training.view",
    },
    "engineer": {
        "apparatus.maintenance",
        "apparatus.view",
        "compliance.view",
        "documents.view",
        "elections.view",
        "events.view",
        "facilities.view",
        "forms.view",
        "inventory.view",
        "locations.view",
        "meetings.view",
        "members.view",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "scheduling.swap",
        "scheduling.view",
        "training.view",
    },
    "lieutenant": {
        "analytics.view",
        "apparatus.maintenance",
        "apparatus.view",
        "audit.view",
        "compliance.view",
        "documents.view",
        "elections.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "events.create",
        "events.edit",
        "events.view",
        "facilities.view",
        "forms.view",
        "fundraising.view",
        "inventory.view",
        "legal.propose",
        "locations.view",
        "meetings.view",
        "members.view",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "positions.view",
        "prospective_members.view",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.view",
        "users.view_contact",
    },
    "captain": {
        "analytics.view",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.view",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.view",
        "elections.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "events.create",
        "events.edit",
        "events.view",
        "facilities.maintenance",
        "facilities.view",
        "forms.view",
        "fundraising.view",
        "inventory.view",
        "legal.propose",
        "locations.view",
        "meetings.view",
        "members.check_in",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "positions.view",
        "prospective_members.manage",
        "prospective_members.view",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.view",
        "users.view_contact",
    },
    "fire_chief": {
        "admin.access",
        "analytics.view",
        "apparatus.approve_driver_exception",
        "apparatus.create",
        "apparatus.delete",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.manage",
        "apparatus.view",
        "audit.export",
        "audit.manage",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.manage",
        "documents.view",
        "elections.manage",
        "elections.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "events.create",
        "events.delete",
        "events.edit",
        "events.manage",
        "events.reopen_attendance",
        "events.view",
        "facilities.create",
        "facilities.delete",
        "facilities.edit",
        "facilities.maintenance",
        "facilities.manage",
        "facilities.view",
        "facilities.view_sensitive",
        "forms.manage",
        "forms.view",
        "fundraising.manage",
        "fundraising.view",
        "integrations.manage",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "legal.propose",
        "legal.publish",
        "locations.create",
        "locations.delete",
        "locations.edit",
        "locations.manage",
        "locations.view",
        "meetings.manage",
        "meetings.view",
        "members.assign_positions",
        "members.check_in",
        "members.create",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.manage",
        "minutes.view",
        "notifications.manage",
        "notifications.view",
        "organization.edit",
        "organization.update_settings",
        "organization.view",
        "orgchart.manage",
        "positions.create",
        "positions.delete",
        "positions.edit",
        "positions.manage_permissions",
        "positions.update",
        "positions.view",
        "prospective_members.manage",
        "prospective_members.view",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "security.manage",
        "settings.edit",
        "settings.manage",
        "settings.manage_contact_visibility",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.create",
        "users.delete",
        "users.edit",
        "users.update_positions",
        "users.view",
        "users.view_contact",
    },
    "deputy_chief": {
        "analytics.view",
        "apparatus.approve_driver_exception",
        "apparatus.create",
        "apparatus.delete",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.manage",
        "apparatus.view",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.manage",
        "documents.view",
        "elections.manage",
        "elections.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "events.create",
        "events.delete",
        "events.edit",
        "events.manage",
        "events.reopen_attendance",
        "events.view",
        "facilities.create",
        "facilities.delete",
        "facilities.edit",
        "facilities.maintenance",
        "facilities.manage",
        "facilities.view",
        "facilities.view_sensitive",
        "forms.manage",
        "forms.view",
        "fundraising.manage",
        "fundraising.view",
        "integrations.manage",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "legal.propose",
        "locations.create",
        "locations.delete",
        "locations.edit",
        "locations.manage",
        "locations.view",
        "meetings.manage",
        "meetings.view",
        "members.assign_positions",
        "members.check_in",
        "members.create",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.manage",
        "minutes.view",
        "notifications.manage",
        "notifications.view",
        "organization.view",
        "positions.view",
        "prospective_members.manage",
        "prospective_members.view",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.create",
        "users.edit",
        "users.update_positions",
        "users.view",
        "users.view_contact",
    },
    "assistant_chief": {
        "analytics.view",
        "apparatus.approve_driver_exception",
        "apparatus.create",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.manage",
        "apparatus.view",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.manage",
        "documents.view",
        "elections.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "events.create",
        "events.edit",
        "events.manage",
        "events.reopen_attendance",
        "events.view",
        "facilities.create",
        "facilities.edit",
        "facilities.maintenance",
        "facilities.manage",
        "facilities.view",
        "facilities.view_sensitive",
        "forms.manage",
        "forms.view",
        "fundraising.view",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "legal.propose",
        "locations.create",
        "locations.edit",
        "locations.manage",
        "locations.view",
        "meetings.manage",
        "meetings.view",
        "members.assign_positions",
        "members.check_in",
        "members.create",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.manage",
        "minutes.view",
        "notifications.manage",
        "notifications.view",
        "organization.view",
        "positions.view",
        "prospective_members.manage",
        "prospective_members.view",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.create",
        "users.edit",
        "users.update_positions",
        "users.view",
        "users.view_contact",
    },
    "president": {
        "admin.access",
        "analytics.view",
        "apparatus.create",
        "apparatus.delete",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.manage",
        "apparatus.view",
        "audit.export",
        "audit.manage",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.manage",
        "documents.view",
        "elections.manage",
        "elections.view",
        "equipment_check.manage",
        "events.create",
        "events.delete",
        "events.edit",
        "events.manage",
        "events.reopen_attendance",
        "events.view",
        "facilities.create",
        "facilities.delete",
        "facilities.edit",
        "facilities.maintenance",
        "facilities.manage",
        "facilities.view",
        "forms.manage",
        "forms.view",
        "fundraising.manage",
        "fundraising.view",
        "integrations.manage",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "legal.propose",
        "legal.publish",
        "locations.create",
        "locations.delete",
        "locations.edit",
        "locations.manage",
        "locations.view",
        "meetings.manage",
        "meetings.view",
        "members.assign_positions",
        "members.check_in",
        "members.create",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.manage",
        "minutes.view",
        "notifications.manage",
        "notifications.view",
        "organization.edit",
        "organization.update_settings",
        "organization.view",
        "orgchart.manage",
        "positions.create",
        "positions.delete",
        "positions.edit",
        "positions.manage_permissions",
        "positions.update",
        "positions.view",
        "prospective_members.manage",
        "reports.manage",
        "reports.view",
        "scheduling.assign",
        "scheduling.manage",
        "scheduling.report",
        "scheduling.swap",
        "scheduling.view",
        "security.manage",
        "settings.edit",
        "settings.manage",
        "settings.manage_contact_visibility",
        "settings.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.create",
        "users.delete",
        "users.edit",
        "users.update_positions",
        "users.view",
        "users.view_contact",
    },
    "vice_president": {
        "analytics.view",
        "apparatus.view",
        "audit.view",
        "compliance.manage",
        "compliance.view",
        "documents.view",
        "elections.manage",
        "elections.view",
        "events.view",
        "facilities.view",
        "facilities.view_sensitive",
        "forms.view",
        "fundraising.manage",
        "fundraising.view",
        "inventory.view",
        "legal.propose",
        "meetings.manage",
        "meetings.view",
        "members.assign_positions",
        "members.check_in",
        "members.manage",
        "members.manage_id_cards",
        "members.view",
        "minutes.manage",
        "minutes.view",
        "notifications.view",
        "organization.view",
        "positions.view",
        "prospective_members.manage",
        "reports.manage",
        "reports.view",
        "scheduling.view",
        "settings.view",
        "training.view",
        "users.view",
        "users.view_contact",
    },
    "quartermaster": {
        "apparatus.view",
        "compliance.view",
        "facilities.view",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "legal.propose",
        "members.view",
        "organization.view",
        "positions.view",
        "settings.view",
        "users.view",
        "users.view_contact",
    },
    "apparatus_officer": {
        "apparatus.create",
        "apparatus.edit",
        "apparatus.maintenance",
        "apparatus.view",
        "compliance.view",
        "equipment_check.manage",
        "equipment_check.submit",
        "equipment_check.view",
        "inventory.manage",
        "inventory.manage_medical",
        "inventory.view",
        "inventory.view_medical",
        "locations.view",
        "members.view",
        "organization.view",
        "positions.view",
        "users.view",
    },
    "facilities_manager": {
        "facilities.create",
        "facilities.edit",
        "facilities.maintenance",
        "facilities.manage",
        "facilities.view",
        "inventory.manage",
        "inventory.view",
        "locations.view",
        "members.view",
        "notifications.view",
        "organization.view",
        "positions.view",
        "users.view",
    },
    "safety_officer": {
        "apparatus.view",
        "compliance.manage",
        "compliance.view",
        "documents.manage",
        "documents.view",
        "events.create",
        "events.edit",
        "events.view",
        "facilities.view",
        "forms.manage",
        "forms.view",
        "inventory.view",
        "locations.view",
        "members.view",
        "notifications.view",
        "organization.view",
        "positions.view",
        "reports.manage",
        "reports.view",
        "training.configure",
        "training.manage",
        "training.view",
        "training.view_all",
        "users.view",
        "users.view_contact",
    },
}


def _load_permissions(raw):
    """Normalize JSON values returned by different database drivers."""
    if isinstance(raw, str):
        raw = json.loads(raw or "[]")
    return list(raw or [])


def upgrade() -> None:
    bind = op.get_bind()
    # Defensive only. ``positions`` IS created by the migration chain — the
    # initial schema builds ``roles`` and 20260805_0008 renames it, which makes
    # that a required ancestor of this revision, so the table is present by the
    # time this runs. Claiming otherwise is the false positive CLAUDE.md
    # pitfall #26 records being reverted after an empirical ``alembic upgrade
    # head`` against an empty database. The guard is kept because it costs one
    # reflection and cannot be wrong, but it is not load-bearing, and it is not
    # the pattern to copy for a genuinely create_all-only table — for those the
    # guard is required.
    if "positions" not in sa.inspect(bind).get_table_names():
        return

    for slug, grants in _BACKFILL.items():
        rows = bind.execute(
            sa.text(
                "SELECT id, permissions FROM positions "
                "WHERE slug = :slug AND is_system = :is_system"
            ),
            {"slug": slug, "is_system": True},
        ).fetchall()

        for row in rows:
            permissions = _load_permissions(row[1])
            # Only a row still carrying exactly the seeded set is ours to
            # rewrite; anything else the department has made its own.
            if set(permissions) != _PRIOR_DEFAULTS[slug]:
                continue
            bind.execute(
                sa.text("UPDATE positions SET permissions = :perms WHERE id = :id"),
                {"perms": json.dumps(permissions + list(grants)), "id": row[0]},
            )


def downgrade() -> None:
    """No-op: this backfill records no provenance, so it cannot revoke safely.

    The upgrade only *appends* grants that were missing, and nothing marks
    which rows it touched. A downgrade that stripped every listed grant from
    every matching system position would also revoke it from organizations
    that onboarded after these grants entered the registry and so always had
    them legitimately — putting the store back out of reach for exactly the
    members this migration exists to serve, on a rollback that was supposed to
    be a no-change.

    Leaving a permission in place is the safe direction for a reversal here:
    the grants are the seeded defaults for these positions either way, and an
    organization that wants them gone can remove them in the position editor.
    """
