"""
Pydantic Schemas

This module exports all Pydantic schemas for the API.
"""

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    UserWithRolesResponse,
    RoleResponse,
    NotificationPreferences,
    ContactInfoUpdate,
    UserProfileResponse,
)
from app.schemas.organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    OrganizationSettings,
    OrganizationSettingsUpdate,
    OrganizationSettingsResponse,
    ContactInfoSettings,
    EmailServiceSettings,
)
from app.schemas.role import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    PermissionDetail,
    PermissionCategory,
    UserRoleAssignment,
    UserRoleResponse,
)
from app.schemas.auth import (
    UserLogin,
    UserRegister,
    TokenResponse,
    TokenRefresh,
    CurrentUser,
    PasswordChange,
    PasswordResetRequest,
    PasswordReset,
    EmailVerification,
    MFASetup,
    MFAVerify,
    MFALogin,
)
from app.schemas.event import (
    EventCreate,
    EventUpdate,
    EventResponse,
    EventListItem,
    EventCancel,
    RSVPCreate,
    RSVPResponse,
    CheckInRequest,
    SelfCheckInRequest,
    EventStats as EventStatistics,
    RecordActualTimes,
    QRCheckInData,
    CheckInMonitoringStats,
)
from app.schemas.election import (
    BallotItem,
    PositionEligibility,
    ElectionBase,
    ElectionCreate,
    ElectionUpdate,
    ElectionResponse,
    ElectionListResponse,
    CandidateBase,
    CandidateCreate,
    CandidateUpdate,
    CandidateResponse,
    CandidateAcceptance,
    VoteCreate,
    VoteResponse,
    CandidateResult,
    PositionResults,
    ElectionResults,
    ElectionStats,
    VoterEligibility,
    BulkVoteCreate,
    EmailBallot,
    EmailBallotResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "UserWithRolesResponse",
    "RoleResponse",
    "NotificationPreferences",
    "ContactInfoUpdate",
    "UserProfileResponse",
    # Organization schemas
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationSettings",
    "OrganizationSettingsUpdate",
    "OrganizationSettingsResponse",
    "ContactInfoSettings",
    "EmailServiceSettings",
    # Role schemas
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "PermissionDetail",
    "PermissionCategory",
    "UserRoleAssignment",
    "UserRoleResponse",
    # Auth schemas
    "UserLogin",
    "UserRegister",
    "TokenResponse",
    "TokenRefresh",
    "CurrentUser",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    "EmailVerification",
    "MFASetup",
    "MFAVerify",
    "MFALogin",
    # Event schemas
    "EventCreate",
    "EventUpdate",
    "EventResponse",
    "EventListItem",
    "EventCancel",
    "RSVPCreate",
    "RSVPResponse",
    "CheckInRequest",
    "SelfCheckInRequest",
    "EventStatistics",
    "RecordActualTimes",
    "QRCheckInData",
    "CheckInMonitoringStats",
    # Election schemas
    "BallotItem",
    "PositionEligibility",
    "ElectionBase",
    "ElectionCreate",
    "ElectionUpdate",
    "ElectionResponse",
    "ElectionListResponse",
    "CandidateBase",
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "CandidateAcceptance",
    "VoteCreate",
    "VoteResponse",
    "CandidateResult",
    "PositionResults",
    "ElectionResults",
    "ElectionStats",
    "VoterEligibility",
    "BulkVoteCreate",
    "EmailBallot",
    "EmailBallotResponse",
]
