import React from 'react';
import {
  AlertTriangle,
  Globe,
  ClipboardCheck,
  Plug,
  Clipboard,
  FileText,
  Send,
} from 'lucide-react';

/** Target fields each integration type expects the user to map. */
export const INTEGRATION_TARGET_FIELDS: Record<string, { key: string; label: string; required: boolean }[]> = {
  membership_interest: [
    { key: 'first_name', label: 'First Name', required: true },
    { key: 'last_name', label: 'Last Name', required: true },
    { key: 'email', label: 'Email', required: true },
    { key: 'phone', label: 'Phone', required: false },
    { key: 'mobile', label: 'Mobile', required: false },
    { key: 'date_of_birth', label: 'Date of Birth', required: false },
    { key: 'address_street', label: 'Street Address', required: false },
    { key: 'address_city', label: 'City', required: false },
    { key: 'address_state', label: 'State', required: false },
    { key: 'address_zip', label: 'ZIP Code', required: false },
    { key: 'interest_reason', label: 'Interest / Reason', required: false },
    { key: 'referral_source', label: 'Referral Source', required: false },
    { key: 'desired_membership_type', label: 'Membership Type', required: false },
  ],
  equipment_assignment: [
    { key: 'member_id', label: 'Member (member_lookup field)', required: true },
    { key: 'item_id', label: 'Item ID', required: true },
    { key: 'reason', label: 'Reason / Notes', required: false },
  ],
  event_registration: [
    { key: 'event_id', label: 'Event ID', required: true },
    { key: 'notes', label: 'Notes', required: false },
  ],
  event_request: [
    { key: 'contact_name', label: 'Contact Name', required: true },
    { key: 'contact_email', label: 'Contact Email', required: true },
    { key: 'contact_phone', label: 'Contact Phone', required: false },
    { key: 'organization_name', label: 'Organization Name', required: false },
    { key: 'outreach_type', label: 'Outreach Type', required: false },
    { key: 'description', label: 'Description', required: false },
    { key: 'preferred_timeframe', label: 'Preferred Date / Timeframe', required: false },
    { key: 'audience_size', label: 'Expected Attendees', required: false },
    { key: 'venue_address', label: 'Venue / Location', required: false },
    { key: 'special_requests', label: 'Special Requests / Notes', required: false },
  ],
};

export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  fields: { label: string; field_type: string; required: boolean; options?: { value: string; label: string }[] }[];
  icon: React.ReactNode;
  color: string;
  isPublic?: boolean;
  integrationHint?: string;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: 'incident-report',
    name: 'Incident Report',
    description: 'Standard incident/accident report form with injury details and witnesses',
    category: 'Safety',
    fields: [
      { label: 'Date of Incident', field_type: 'date', required: true },
      { label: 'Time of Incident', field_type: 'time', required: true },
      { label: 'Location', field_type: 'text', required: true },
      { label: 'Type of Incident', field_type: 'select', required: true },
      { label: 'Description', field_type: 'textarea', required: true },
      { label: 'Injuries Reported', field_type: 'radio', required: true },
      { label: 'Injury Details', field_type: 'textarea', required: false },
      { label: 'Witnesses', field_type: 'textarea', required: false },
      { label: 'Equipment Involved', field_type: 'text', required: false },
      { label: 'Immediate Actions Taken', field_type: 'textarea', required: true },
      { label: 'Follow-Up Required', field_type: 'checkbox', required: false },
      { label: 'Photos Attached', field_type: 'file', required: false },
      { label: 'Reported By', field_type: 'text', required: true },
      { label: 'Supervisor Notified', field_type: 'radio', required: true },
      { label: 'Additional Notes', field_type: 'textarea', required: false },
    ],
    icon: <AlertTriangle className="w-6 h-6" aria-hidden="true" />,
    color: 'text-red-700 dark:text-red-400',
  },
  {
    id: 'membership-interest',
    name: 'Membership Interest Form',
    description: 'Public form for prospective members to express interest in joining your department',
    category: 'Administration',
    fields: [
      { label: 'First Name', field_type: 'text', required: true },
      { label: 'Last Name', field_type: 'text', required: true },
      { label: 'Email Address', field_type: 'email', required: true },
      { label: 'Phone Number', field_type: 'phone', required: true },
      { label: 'Date of Birth', field_type: 'date', required: false },
      { label: 'Street Address', field_type: 'text', required: false },
      { label: 'City', field_type: 'text', required: false },
      { label: 'State', field_type: 'text', required: false },
      { label: 'Zip Code', field_type: 'text', required: false },
      { label: 'Membership Type', field_type: 'select', required: false, options: [
        { value: 'regular', label: 'Regular Member' },
        { value: 'administrative', label: 'Administrative Member' },
      ] },
      { label: 'Previous Fire/EMS Experience', field_type: 'radio', required: true },
      { label: 'Experience Details', field_type: 'textarea', required: false },
      { label: 'Why are you interested in joining?', field_type: 'textarea', required: true },
      { label: 'How did you hear about us?', field_type: 'select', required: false },
      { label: 'Availability', field_type: 'select', required: true },
      { label: 'Additional Information', field_type: 'textarea', required: false },
    ],
    icon: <Globe className="w-6 h-6" aria-hidden="true" />,
    color: 'text-cyan-700 dark:text-cyan-400',
    isPublic: true,
    integrationHint: 'membership_interest',
  },
  {
    id: 'equipment-inspection',
    name: 'Equipment Inspection',
    description: 'Pre-use and periodic equipment inspection checklist',
    category: 'Operations',
    fields: [
      { label: 'Equipment Name', field_type: 'text', required: true },
      { label: 'Serial Number', field_type: 'text', required: true },
      { label: 'Inspection Date', field_type: 'date', required: true },
      { label: 'Inspector', field_type: 'text', required: true },
      { label: 'Visual Condition', field_type: 'select', required: true },
      { label: 'Functional Test', field_type: 'radio', required: true },
      { label: 'Safety Features Check', field_type: 'radio', required: true },
      { label: 'Cleanliness', field_type: 'select', required: true },
      { label: 'Defects Found', field_type: 'textarea', required: false },
      { label: 'Action Required', field_type: 'textarea', required: false },
      { label: 'Pass/Fail', field_type: 'radio', required: true },
      { label: 'Next Inspection Due', field_type: 'date', required: false },
    ],
    icon: <ClipboardCheck className="w-6 h-6" aria-hidden="true" />,
    color: 'text-emerald-700 dark:text-emerald-400',
  },
  {
    id: 'equipment-assignment',
    name: 'Equipment Assignment',
    description: 'Quartermaster form for assigning equipment to members - integrates with inventory',
    category: 'Operations',
    fields: [
      { label: 'Assigned Member', field_type: 'member_lookup', required: true },
      { label: 'Equipment Item', field_type: 'text', required: true },
      { label: 'Serial/Asset Number', field_type: 'text', required: true },
      { label: 'Assignment Date', field_type: 'date', required: true },
      { label: 'Assignment Type', field_type: 'select', required: true },
      { label: 'Condition at Assignment', field_type: 'select', required: true },
      { label: 'Expected Return Date', field_type: 'date', required: false },
      { label: 'Reason for Assignment', field_type: 'textarea', required: false },
      { label: 'Acknowledgment', field_type: 'checkbox', required: true },
      { label: 'Notes', field_type: 'textarea', required: false },
    ],
    icon: <Plug className="w-6 h-6" aria-hidden="true" />,
    color: 'text-orange-700 dark:text-orange-400',
    integrationHint: 'equipment_assignment',
  },
  {
    id: 'vehicle-check',
    name: 'Apparatus Check-off',
    description: 'Daily apparatus/vehicle check-off form',
    category: 'Operations',
    fields: [
      { label: 'Apparatus Number', field_type: 'text', required: true },
      { label: 'Date', field_type: 'date', required: true },
      { label: 'Shift', field_type: 'select', required: true },
      { label: 'Checked By', field_type: 'text', required: true },
      { label: 'Mileage', field_type: 'number', required: true },
      { label: 'Fuel Level', field_type: 'select', required: true },
      { label: 'Engine Oil', field_type: 'radio', required: true },
      { label: 'Coolant Level', field_type: 'radio', required: true },
      { label: 'Tire Condition', field_type: 'radio', required: true },
      { label: 'Lights & Sirens', field_type: 'radio', required: true },
      { label: 'Pump Test', field_type: 'radio', required: true },
      { label: 'Hose Inventory', field_type: 'radio', required: true },
      { label: 'SCBA Check', field_type: 'radio', required: true },
      { label: 'Medical Supplies', field_type: 'radio', required: true },
      { label: 'Tools & Equipment', field_type: 'radio', required: true },
      { label: 'Radio Check', field_type: 'radio', required: true },
      { label: 'Body/Cab Condition', field_type: 'radio', required: true },
      { label: 'Deficiencies Found', field_type: 'textarea', required: false },
      { label: 'Actions Taken', field_type: 'textarea', required: false },
      { label: 'Overall Status', field_type: 'radio', required: true },
    ],
    icon: <Clipboard className="w-6 h-6" aria-hidden="true" />,
    color: 'text-blue-700 dark:text-blue-400',
  },
  {
    id: 'member-feedback',
    name: 'Member Feedback Survey',
    description: 'Anonymous feedback survey for department improvement',
    category: 'Administration',
    fields: [
      { label: 'Overall Satisfaction', field_type: 'radio', required: true },
      { label: 'Training Quality', field_type: 'radio', required: true },
      { label: 'Equipment Availability', field_type: 'radio', required: true },
      { label: 'Leadership Effectiveness', field_type: 'radio', required: true },
      { label: 'Communication Quality', field_type: 'radio', required: true },
      { label: 'What is working well?', field_type: 'textarea', required: false },
      { label: 'What needs improvement?', field_type: 'textarea', required: false },
      { label: 'Suggestions for training topics', field_type: 'textarea', required: false },
      { label: 'Equipment requests', field_type: 'textarea', required: false },
      { label: 'Additional comments', field_type: 'textarea', required: false },
    ],
    icon: <FileText className="w-6 h-6" aria-hidden="true" />,
    color: 'text-purple-700 dark:text-purple-400',
  },
  {
    id: 'community-event-request',
    name: 'Community Event Request',
    description: 'Public form for community members to request fire department participation at events',
    category: 'Administration',
    fields: [
      { label: 'Contact Name', field_type: 'text', required: true },
      { label: 'Contact Email', field_type: 'email', required: true },
      { label: 'Contact Phone', field_type: 'phone', required: false },
      { label: 'Organization Name', field_type: 'text', required: false },
      { label: 'Outreach Type', field_type: 'select', required: true },
      { label: 'Description', field_type: 'textarea', required: true },
      { label: 'Preferred Timeframe', field_type: 'text', required: false },
      { label: 'Time of Day', field_type: 'select', required: false },
      { label: 'Expected Attendees', field_type: 'number', required: false },
      { label: 'Age Group', field_type: 'select', required: false },
      { label: 'Venue Address', field_type: 'text', required: false },
      { label: 'Special Requests', field_type: 'textarea', required: false },
    ],
    icon: <Send className="w-6 h-6" aria-hidden="true" />,
    color: 'text-teal-700 dark:text-teal-400',
    isPublic: true,
    integrationHint: 'event_request',
  },
];
