import { chromium } from "@playwright/test";
import { DEMO_MEMBER_CREDENTIALS } from "./manifest.mjs";
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_BROWSERS_PATH + "/chromium" });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await page.goto("http://localhost:3000/login", { waitUntil: "domcontentloaded" });
await page.fill('input[name="username"], input#username', DEMO_MEMBER_CREDENTIALS.username);
await page.fill('input[name="password"], input#password', DEMO_MEMBER_CREDENTIALS.password);
await page.click('button[type="submit"]');
await page.waitForTimeout(4000);
const info = await page.evaluate(async () => {
  const r = await fetch("/api/v1/events?limit=50", { credentials: "include" });
  const b = await r.json();
  const list = b.events || b.items || b;
  const now = new Date().toISOString();
  const e = list.find((x) => (x.requires_rsvp ?? x.requiresRsvp) && (x.start_datetime ?? x.startDatetime) > now);
  return { id: e?.id, rsvp: e?.user_rsvp_status ?? e?.userRsvpStatus, count: list.length };
});
console.log(JSON.stringify(info));
await page.goto(`http://localhost:3000/events/${info.id}`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(4000);
console.log("BUTTONS:", (await page.locator("button").allInnerTexts()).map(t=>t.trim()).filter(Boolean).slice(0,40).join(" | "));
await browser.close();
