"""
Department Officer Endpoints

Manages which member holds each department office.  The resolved directory
feeds the ``{{president_name}}`` / ``{{chief_title}}`` template variables so a
notice generated by any member is still signed by the officeholder.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from loguru import logger
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import require_permission
from app.core.audit import log_audit_event
from app.core.database import get_db
from app.core.utils import safe_error_detail
from app.models.user import User
from app.schemas.officer import (
    OfficerDirectoryResponse,
    OfficerUpdate,
)
from app.services.officer_service import OfficerService, build_office_variables

router = APIRouter()

# Every handler declares the same gate as the email templates screen the
# directory is edited from. Spelled out per handler rather than hoisted into a
# shared constant so the AST-based auth-coverage guard
# (tests/test_endpoint_auth_coverage.py) can see it.


@router.get("", response_model=OfficerDirectoryResponse)
async def list_officers(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(
        require_permission("settings.manage", "organization.update_settings")
    ),
):
    """List every department office with its current holder.

    Loading this screen also refreshes the render-time directory cached on the
    organization, so a member who renamed themselves or changed their email is
    picked up without an explicit re-save.
    """
    service = OfficerService(db)
    resolved = await service.resolve(current_user.organization_id)
    await service.sync_directory(current_user.organization_id, resolved)
    await db.commit()
    return OfficerDirectoryResponse(
        offices=resolved,
        variables=build_office_variables(),
    )


@router.put("/{office_key}", response_model=OfficerDirectoryResponse)
async def set_officer(
    office_key: str,
    payload: OfficerUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(
        require_permission("settings.manage", "organization.update_settings")
    ),
):
    """Assign a member (and/or overrides) to a department office."""
    service = OfficerService(db)
    try:
        resolved = await service.set_officer(
            current_user.organization_id,
            office_key,
            user_id=payload.user_id,
            display_name=payload.display_name,
            title=payload.title,
            email=payload.email,
            phone=payload.phone,
            updated_by=current_user.id,
        )
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail=safe_error_detail(e)
        )

    await log_audit_event(
        db=db,
        event_type="organization_officer_assigned",
        event_category="administration",
        severity="info",
        event_data={
            "office_key": office_key,
            "assigned_user_id": payload.user_id,
            "has_name_override": bool(payload.display_name),
        },
        user_id=str(current_user.id),
        username=current_user.username,
    )
    await db.commit()

    logger.info(
        "Department office {} assigned org={} by={}",
        office_key,
        current_user.organization_id,
        current_user.id,
    )
    return OfficerDirectoryResponse(
        offices=resolved,
        variables=build_office_variables(),
    )


@router.delete("/{office_key}", response_model=OfficerDirectoryResponse)
async def clear_officer(
    office_key: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(
        require_permission("settings.manage", "organization.update_settings")
    ),
):
    """Clear an office assignment, falling back to position auto-detection."""
    service = OfficerService(db)
    try:
        resolved = await service.clear_officer(current_user.organization_id, office_key)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail=safe_error_detail(e)
        )

    await log_audit_event(
        db=db,
        event_type="organization_officer_cleared",
        event_category="administration",
        severity="info",
        event_data={"office_key": office_key},
        user_id=str(current_user.id),
        username=current_user.username,
    )
    await db.commit()

    return OfficerDirectoryResponse(
        offices=resolved,
        variables=build_office_variables(),
    )
